### ISSUE TITLE
issue with !commands :/

### ISSUE THREAD

**Issue by NaruuMrPink** [LittleBigBug/chat-cosmetics#1]
http://forums.ulyssesmod.net/index.php/topic,8702.msg45365.html#msg45365 <-- the first issue is here.
But now a new error occured x)

--------------------------------

[ERROR] addons/chat-cosmetics-master/lua/autorun/client/cl_chattags.lua:82: bad argument #1 to 'find' (string expected, got nil)
  1. find - [C]:-1
   2. fn - addons/chat-cosmetics-master/lua/autorun/client/cl_chattags.lua:82
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

Naruu # Mr. Pink: !commands

-----------------------------------

You are doing a great job and you have my full support :3

Good luck

**Comment by LittleBigBug** [comment]
Try adding me on steam. I have thought I fixed this earlier. Try re-downloading the repo.
http://www.steamcommunity.com/id/littlebigbug
