### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by loaf2001** [LittleBigBug/chat-cosmetics#12]
Couldn't find 'autorun/client/cl_chattags.lua' (@addons/chat-cosmetics-master/lua/autorun/server/sv_chattags.lua (line 1))

**Comment by LittleBigBug** [comment]
https://github.com/LittleBigBug/chat-cosmetics/commit/33a3bd3535df13386c4846418cf15de48a98e4b9

This plugin is super old, and very inefficient. I'll plan on rewriting this whole thing soon.
