### ISSUE TITLE
Bracket colors?

### ISSUE THREAD

**Issue by omazssa** [LittleBigBug/chat-cosmetics#13]
One of my bracket colors is different from the other for all chat tags
so its like

[-light blue (name) ]-whatever the other color is : chat 

could someone help me change the color of the tag to the other color?

**Comment by LittleBigBug** [comment]
At the moment there is no support for that.
I can add something quickly but I am actually rewriting this whole thing so, it should be out in a little
Add me on steam if you want.
https://steamcommunity.com/id/littlebigbug
