### ISSUE TITLE
Just not working.

### ISSUE THREAD

**Issue by UndeadVandal** [LittleBigBug/chat-cosmetics#14]
It worked originally when I put it in and it actually saved me :D but the next day it no longer worked, no errors or anything just doesnt work.

heres my chat tags 

`-- _PRIORITY = 9998
-- Chat Cosmetics Created and Developed by LittleBigBug
-- http://www.steamcommunity.com/id/littlebigbug
-- All Rights reserved
-- Specially developed for Aero Game Servers
-- Aerogameservers.com

-- _-----------------------------_
-- Chat Cosmetics Configuration
-- _-----------------------------_
-- --_________________--

CUConfig = {}
CUConfig.Tags = {}

CUConfig.Debug = false -- For testing - prints in console

local color_white = color_white

-- /\ DONT TOUCH ABOVE /\

-- Start Editing Below

CUConfig.MessagePrefix = nil -- Message prefix for the messages. Nil is default: [Server]
CUConfig.PrefixColor = Color(0, 255, 168)

CUConfig.EnableConnectMessage = false -- Enables "Player <playername> has connected to the server" in chat when anyone joins.
CUConfig.EnableFirstSpawnMessage = false -- Enables "Player <playername> has Spawned in the server" in chat when anyone finishes loading in the server.

CUConfig.EnableDisconnectMessage = false -- Enables "Player <playername> has disconnected from the server" in the chat when anyone leaves.

CUConfig.EnableAdminSteamDisconnect = false -- Enables "Player <playername> had the steamid of <SteamID>" in the chat to all admins and superadmins when the player disconnects

CUConfig.AdminSteamGroups = { -- Groups to show the disconnecting players steamid to

["superadmin"] = 1,
["admin"] = 1

}

CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = false -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 48, 255, 162 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Dev" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_white -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:0:52985450"] = 1, -- LittleBigBug
["STEAM_0:1:7099"] = 2 -- Garry

}

-- Chat Tags
-- These do work with almost every gamemode.
-- Tested Gamemodes:
-- Deathrun, DarkRP
-- OOC, Advert, and PM work.

if maestro ~= nil then

	CUConfig.Tags["root"] = { 
		Color( 255, 0, 0 ),
		"Root", 
		color_white, 
		Color( 255, 94, 94 ) 
	}

end

CUConfig.Tags["superadmin"] = { -- Group name in the ""
	Color( 137, 68, 224, 255 ), -- The color of the tag
	"Owner", -- What to display in the tag
	color_white, -- The brackets color of the tag
	Color( 255, 94, 94 ) -- Chat color, or if you don't want a specific chat color, use 'false' (WILL NOT OVVERIDE /advert CHAT COLOR!)
}

CUConfig.Tags["StaffManager"] = {
	Color( 239, 25, 25, 255 ),
	"StaffDirector",
	color_white,
	false
}

CUConfig.Tags["Developer"] = {
	Color(239, 25, 25, 255), 
	"Dev", 
	color_white, 
	false 
}

CUConfig.Tags["CommunityOwner"] = {
	Color(210, 0, 244, 255), 
	"CommunityOwner", 
	color_white, 
	false 
}

CUConfig.Tags["SupAdmin"] = {
	Color(255, 0, 244, 255), 
	"SuperAdmin", 
	color_white, 
	false 
}

CUConfig.Tags["admin"] = {
	Color(255, 0, 244, 255), 
	"Admin", 
	color_white, 
	false 
}

CUConfig.Tags["Moderator"] = {
	Color(19, 0, 244, 255), 
	"Moderator", 
	color_white, 
	false 
}

CUConfig.Tags["TrialStaff"] = {
	Color(19, 0, 244, 255), 
	"TrialStaff", 
	color_white, 
	false 
}

CUConfig.Tags["Supporter"] = {
	Color(11, 206, 54, 255), 
	"Supporter", 
	color_white, 
	false 
}

CUConfig.Tags["VIPGold"] = {
	Color(153, 147, 9, 255), 
	"VIPGold", 
	color_white, 
	false 
}

CUConfig.Tags["VIP"] = {
	Color(0, 193, 255, 255), 
	"VIP", 
	color_white, 
	false 
}

CUConfig.BracketLeft = "[" -- the bracket on the right of the tag. You can leave this blank
CUConfig.BracketRight = "] " -- and this one like | as a seperator.

CUConfig.AdvertChatColor = Color( 222, 242, 0, 255 ) -- Color For /advert chats (DarkRP only - just leave this alone if you don't use DarkRP)`

Not sure what else you would need. Thanks alot and great job on the script!

**Comment by LittleBigBug** [comment]
if the `` on the first and last characters are not in the actual file, remove those
On another note, I'll let you know that I'm grateful that someone else is using my plugin and that I am rewriting it.
It may take a while because it is not on the top of my priorities.

**Comment by UndeadVandal** [comment]
They `` arent actually there that was the thing to make it it 'code' format. Anyhow I'm understanding it's a bug?

Thanks for the reply I'll be looking forward to the rewrite!

**Comment by UndeadVandal** [comment]
alrighty i did

**Comment by LittleBigBug** [comment]
Ok sorry, I am super busy with finals and stuff, I will try to get on steam
soon.
Cheers
Sorry for the inconvenience
