### ISSUE TITLE
adding custom tags

### ISSUE THREAD

**Issue by joshua-leandoer** [LittleBigBug/chat-cosmetics#16]
how can i possibly add my own tags and not just "superadmin" "admin" and "user" I would like to add my own group chat tags such as "donator" or "owner"

**Comment by LittleBigBug** [comment]
Yeah don't worry it's simple just copy one of those and just paste and configure :)

**Comment by joshua-leandoer** [comment]
Yo i did that and every group i talk in, they all say "SuperAdmin"

**Comment by LittleBigBug** [comment]
Then could you post your config onto pastebin or something and post that here?

**Comment by joshua-leandoer** [comment]
ok

**Comment by joshua-leandoer** [comment]
http://pastebin.com/YJQ2YCPp

**Comment by LittleBigBug** [comment]
So for every user they say SuperAdmin?
Could you send a screenshot of the chat for me?

**Comment by joshua-leandoer** [comment]
yes i am in the "ceo" group and added that to the config file and i get this
http://steamcommunity.com/sharedfiles/filedetails/?id=881926561

**Comment by LittleBigBug** [comment]
Ok. Can you show me every addon you have installed? I think that those tags aren't my plugin

**Comment by joshua-leandoer** [comment]
yeah man 1 sec

**Comment by joshua-leandoer** [comment]
ok so i have a lot of addons on my server i checked them all theyre all models or tools

**Comment by joshua-leandoer** [comment]
tools like third person or sitting script

**Comment by LittleBigBug** [comment]
Whats your server's IP?

**Comment by joshua-leandoer** [comment]
185.38.148.134:27115

**Comment by joshua-leandoer** [comment]
actually i dont think its your addon i have no chat tags installed even reinstalled ulx and its the same thing idk whats going on

**Comment by LittleBigBug** [comment]
Haha ok if you want I'll join later today and have a look. Can you screenshot your addons folder for me please?

**Comment by LittleBigBug** [comment]
[#91eef87](https://github.com/LittleBigBug/chat-cosmetics/commit/91eef87aa588817a6368a8cfcb06038044859702)
