### ISSUE TITLE
Chat cosmetics breaks my chat

### ISSUE THREAD

**Issue by mysteriousrunt** [LittleBigBug/chat-cosmetics#18]
I don't know if I'm doing this wrong or something, but when I try to type a message my chat doesnt even come up. In console the error is
[ERROR] addons/chat-cosmetics/lua/chatcosmetics/client/chatmodify.lua:20: attempt to index local 'ptag' (a nil value)
  1. fn - addons/chat-cosmetics/lua/chatcosmetics/client/chatmodify.lua:20
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:109
    3. func - gamemodes/darkrp/gamemode/modules/chat/cl_chat.lua:30
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by LittleBigBug** [comment]
Seems like that player doesn't have a tag assigned at all, I might have not added a check for that. Are there any groups that are not assigned a tag?
If you want me to respond faster add me on steam
https://steamcommunity.com/id/littlebigbug

**Comment by mysteriousrunt** [comment]
Yeah that was the problem, thanks for helping!

**Comment by LittleBigBug** [comment]
Of course, enjoy the plugin :)
