### ISSUE TITLE
Error with chat cosmetics. 

### ISSUE THREAD

**Issue by ipanda0** [LittleBigBug/chat-cosmetics#19]
[ERROR] lua/chatcosmetics/client/chatmodify.lua:20: attempt to index local 'ptag' (a nil value)
  1. fn - lua/chatcosmetics/client/chatmodify.lua:20
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

This is the error I'm getting, if you need any more information please say!

**Comment by LittleBigBug** [comment]
#6f7b33d
