### ISSUE TITLE
Chat Prefix error

### ISSUE THREAD

**Issue by Gordon301** [LittleBigBug/chat-cosmetics#2]
Hello!

I have been using your addon allot recently as I find it is super useful on my DarkRP server.
However. I am currently experiencing an odd issue where the prefix and what I am typing shows up. But the name of the person typing doesn't appear. It also doesn't seem to register any ULX commands.

eg: "[Owner] : test"
![image](https://cloud.githubusercontent.com/assets/14040913/9567489/d97c1f08-4f24-11e5-9a84-0c67f9bb3da8.png)

Thanks
//Gordon

**Comment by LittleBigBug** [comment]
This had worked before?
