### ISSUE TITLE
Two issues:

### ISSUE THREAD

**Issue by TheCrossBoy** [LittleBigBug/chat-cosmetics#6]
Hello! Thanks for reading. So i recently installed this and it is amazing. Thank you so much for making this. I realize this is probably old and everything, but I hope you can still help me. So here are my two problems:

1. With the chat tags that only affect certain people, It only detects whatever tag is on the bottom, not the top or anything in between. I'll paste the config in a response to the topic, so its easier to read. 

2. When I use gmod's rcon command and use the "say" command (i.e. rcon say Hello!) It gives me this error:
 [ERROR] addons/chat-cosmetics-master/lua/autorun/client/cl_chattags.lua:40: attempt to call method 'SteamID' (a nil value)
  1. fn - addons/chat-cosmetics-master/lua/autorun/client/cl_chattags.lua:40
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

Thanks in advance.

**EDIT**: I am running deathrun, in case you were wondering.

**Comment by TheCrossBoy** [comment]
-- _PRIORITY = 9998
-- Chat Cosmetics Created and Developed by LittleBigBug
-- http://www.steamcommunity.com/id/littlebigbug
-- All Rights reserved
-- Specially developed for Aero Game Servers
-- Aerogameservers.com

-- _-----------------------------_
-- Chat Cosmetics Configuration
-- _-----------------------------_
-- --_________________--

CUConfig = {}
CUConfig.Tags = {}

CUConfig.Debug = false -- For testing - prints in console

local color_white = color_white

-- /\ DONT TOUCH ABOVE /\

-- Start Editing Below

CUConfig.MessagePrefix = nil -- Message prefix for the messages. Nil is default: [Server]
CUConfig.PrefixColor = Color(0, 255, 168)

CUConfig.EnableConnectMessage = true -- Enables "Player <playername> has connected to the server" in chat when anyone joins.
CUConfig.EnableFirstSpawnMessage = false -- Enables "Player <playername> has Spawned in the server" in chat when anyone finishes loading in the server.

CUConfig.EnableDisconnectMessage = false -- Enables "Player <playername> has disconnected from the server" in the chat when anyone leaves.

CUConfig.EnableAdminSteamDisconnect = true -- Enables "Player <playername> had the steamid of <SteamID>" in the chat to all admins and superadmins when the player disconnects


CUConfig.AdminSteamGroups = { -- Groups to show the disconnecting players steamid to

["senioradmin"] = 1,
["owner"] = 1

}

CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = false -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 48, 255, 162 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Dev" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_white -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:0:52985450"] = 1, -- LittleBigBug
["STEAM_0:1:7099"] = 2 -- Garry

}

CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = true -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 255, 29, 180 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Da Pink Princess" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_white -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:1:85925061"] = 3, -- Saints

}

CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = true -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 0, 49, 0 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Crossy" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_black -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:0:113902473"] = 4, -- Crossy

}

CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = true -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 0, 127, 255 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Senpaierino" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_white -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:1:99218980"] = 5, -- Senpai

}

-- Chat Tags
-- These do work with almost every gamemode.
-- Tested Gamemodes:
-- Deathrun, DarkRP
-- OOC, Advert, and PM work.

if maestro ~= nil then

	CUConfig.Tags["root"] = { 
		Color( 255, 0, 0 ),
		"Root", 
		color_white, 
		Color( 255, 94, 94 ) 
	}

end

CUConfig.Tags["owner"] = {
	Color(188, 3, 0), 
	"Owner", 
	color_black, 
	Color( 255, 94, 94 ) 
}

CUConfig.Tags["senioradmin"] = { -- Group name in the ""
	Color( 108, 0, 0 ), -- The color of the tag
	"Sr. Admin", -- What to display in the tag
	color_black, -- The brackets color of the tag
	Color( 255, 94, 94 ) -- Chat color, or if you don't want a specific chat color, use 'false' (WILL NOT OVVERIDE /advert CHAT COLOR!)
}

CUConfig.Tags["admin"] = {
	Color( 255, 0, 0 ),
	"Admin",
	color_black,
	Color( 255, 94, 94 )
}

CUConfig.Tags["jradmin"] = {
	Color(255, 64, 59), 
	"Jr. Admin", 
	color_white, 
	false 
}

CUConfig.Tags["mod"] = {
	Color(0, 0, 255), 
	"Moderator", 
	color_white, 
	false 
}

CUConfig.Tags["jrmod"] = {
	Color(127, 255, 0), 
	"Jr. Mod", 
	color_white, 
	false 
}

CUConfig.Tags["veteran"] = {
	Color(0, 186, 210), 
	"Veteran", 
	color_white, 
	false 
}

CUConfig.Tags["trusted"] = {
	Color(243, 223, 0), 
	"Trusted", 
	color_white, 
	false 
}

CUConfig.Tags["regular"] = {
	Color(255, 128, 0), 
	"Regular", 
	color_white, 
	false 
}

CUConfig.Tags["user"] = {
	Color(138, 138, 138), 
	"Guest", 
	color_white, 
	false 
}

CUConfig.BracketLeft = "[" -- the bracket on the right of the tag. You can leave this blank
CUConfig.BracketRight = "] " -- and this one like | as a seperator.

CUConfig.AdvertChatColor = Color( 0, 255, 238 ) -- Color For /advert chats (DarkRP only - just leave this alone if you don't use DarkRP)

**Comment by LittleBigBug** [comment]
Hello! And I am still providing support, but I am confused my what you mean on your first issue. I can fix the second one soon.

**Comment by TheCrossBoy** [comment]
CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = true -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 0, 49, 0 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Crossy" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_black -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:0:113902473"] = 4, -- Crossy

}

CUConfig.CustomTag = { }
CUConfig.CustomTag.Enabled = true -- Enable the additional chat tags to only affect specific SteamIDS. Will be shown before the group tag.
CUConfig.CustomTag.Colour = Color( 0, 127, 255 ) -- Color of the tag (not the brackets)
CUConfig.CustomTag.Name = "Senpaierino" -- What to display in the tag
CUConfig.CustomTag.BracketsColour = color_white -- The bracket colors of the tag
CUConfig.CustomTag.BracketLeft = "[" -- The bracket or the right of the tag You could leave this blank
CUConfig.CustomTag.BracketRight = "]" -- and instead just use | as a seperator ( Admin | LittleBigBug: Hi!)
CUConfig.CustomTag.SteamIDs = { -- List of steamids to assign the Tag to.

["STEAM_0:1:99218980"] = 5, -- Senpai

}

Sorry! It's these, whenever I add one, you may notice that I have multiple, it only actually uses whichever one is on the bottom, for example if I had the one that is "Crossy" on the bottom, it would put [Cross] before their name, but not anyone else's. If I were to move the "Senpai" tag to the bottom, it would put [Senpaierino] before the correct person's name, but the [Crossy] one would no longer work. (No I'm not trying to give the same person two different tags)

**Comment by LittleBigBug** [comment]
You can't add multiple. What you're doing is overriding the "Crossy" one :P I am rewriting this from scratch to add multiple at some point haha Sorry.

But the console bug should be fixed now

**Comment by LittleBigBug** [comment]
You can't add multiple. What you're doing is overriding the "Crossy" one :P I am rewriting this from scratch to add multiple at some point haha Sorry.

But the console bug should be fixed now

**Comment by TheCrossBoy** [comment]
Thanks!

**Comment by LittleBigBug** [comment]
Yep! Enjoy my plugin. :)
