### ISSUE TITLE
DarkRP errors

### ISSUE THREAD

**Issue by kaykayy** [LittleBigBug/chat-cosmetics#7]
[ERROR] addons/chat cosmetics/lua/autorun/client/cl_chattags.lua:31: attempt to call method 'Team' (a nil value)
  1. fn - addons/chat cosmetics/lua/autorun/client/cl_chattags.lua:31
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[ERROR] addons/chat cosmetics/lua/autorun/client/cl_chattags.lua:37: attempt to index local 'tag' (a nil value)
  1. fn - addons/chat cosmetics/lua/autorun/client/cl_chattags.lua:37
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:110
    3. func - workshop/gamemodes/darkrp/gamemode/modules/chat/cl_chat.lua:28
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by LittleBigBug** [comment]
What exactly are you doing as this is happening?

**Comment by kaykayy** [comment]
Just opening the chat
also pops up when trying to team chat

**Comment by LittleBigBug** [comment]
Can I see your configuration?

**Comment by kaykayy** [comment]
It was a fresh install

**Comment by kaykayy** [comment]
Nothing edited

**Comment by LittleBigBug** [comment]
What addons do you have installed on your server?

**Comment by kaykayy** [comment]
http://i.imgur.com/Nr4Cvef.png

**Comment by kaykayy** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=218345306

**Comment by LittleBigBug** [comment]
Sorry for late comments. I am not sure what is wrong here. What is your server IP?

**Comment by kaykayy** [comment]
45.121.211.15:27410
