### ISSUE TITLE
Chat cosmetics not working

### ISSUE THREAD

**Issue by oOSpeedhackerOo** [LittleBigBug/chat-cosmetics#8]
So i recently started up a darkrp server and installed everything i needed (including chat cosmetics)
It worked quiet well since today.
After i restarted my server after changing some jobs it just doesn't work.
I already reversed all my changes but nothing happened.
There are no errors or problems neither in my console nor the server logs

**Comment by LittleBigBug** [comment]
If there are no errors I am not sure. Although I could say make sure the files are being ran. Go into every file and type at the top of each print("shdshgssnsj") or something and tell me if something prints
