### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FlushaDev** [LittleBigBug/chat-cosmetics#9]
I placed the whole folder in my server's addon folder and did not edit anything, after I restarted still nothing worked. Please help
Here's a screenshot of my server's addon folder:
https://gyazo.com/cb09da169cbf487dd8efade1040dc310
Thanks

**Comment by LittleBigBug** [comment]
Sorry for the late reply! Could you enter the chatcosmetics folder you have there?

**Comment by FlushaDev** [comment]
I fixed it. It was a mistake in the color codes in the config. :D
